// ─── BRAND COLORS ────────────────────────────────────────────────────────────
export const C = {
  primary: "#1565C0",
  primaryLight: "#E3F2FD",
  primaryDark: "#0D47A1",
  accent: "#00ACC1",
  success: "#2E7D32",
  successBg: "#E8F5E9",
  warn: "#E65100",
  warnBg: "#FFF3E0",
  danger: "#C62828",
  dangerBg: "#FFEBEE",
  bg: "#F0F4F8",
  card: "#FFFFFF",
  text: "#1A237E",
  textSec: "#546E7A",
  border: "#CFD8DC",
};

// ─── SHARED STYLES ────────────────────────────────────────────────────────────
export const S = {
  page: { minHeight: "100vh", background: C.bg, fontFamily: "'Segoe UI', system-ui, sans-serif", color: "#1a1a2e" },
  nav: { background: C.primary, boxShadow: "0 2px 8px rgba(21,101,192,0.3)", position: "sticky", top: 0, zIndex: 100 },
  navInner: { maxWidth: "1100px", margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-between", height: "62px", padding: "0 20px", flexWrap: "wrap", gap: "8px" },
  logo: { fontSize: "20px", fontWeight: "800", color: "#fff", cursor: "pointer", letterSpacing: "-0.3px", display: "flex", alignItems: "center", gap: "8px" },
  navLinks: { display: "flex", gap: "4px", alignItems: "center", flexWrap: "wrap" },
  navLink: { padding: "7px 13px", borderRadius: "8px", cursor: "pointer", fontSize: "13px", color: "rgba(255,255,255,0.8)", fontWeight: "500", border: "none", background: "transparent" },
  navActive: { background: "rgba(255,255,255,0.2)", color: "#fff" },
  container: { maxWidth: "1100px", margin: "0 auto", padding: "0 20px" },
  pageBody: { padding: "36px 20px", maxWidth: "1100px", margin: "0 auto" },
  card: { background: C.card, border: `1px solid ${C.border}`, borderRadius: "14px", padding: "24px", marginBottom: "20px", boxShadow: "0 1px 4px rgba(0,0,0,0.06)" },
  formWrap: { minHeight: "90vh", display: "flex", alignItems: "center", justifyContent: "center", padding: "30px 20px", background: C.bg },
  formCard: { background: C.card, border: `1px solid ${C.border}`, borderRadius: "18px", padding: "36px 32px", width: "100%", maxWidth: "440px", boxShadow: "0 4px 24px rgba(21,101,192,0.1)" },
  label: { display: "block", fontSize: "12px", fontWeight: "700", color: C.textSec, marginBottom: "5px", textTransform: "uppercase", letterSpacing: "0.5px" },
  input: { width: "100%", padding: "11px 13px", background: C.bg, border: `1.5px solid ${C.border}`, borderRadius: "9px", color: "#1a1a2e", fontSize: "14px", outline: "none", boxSizing: "border-box" },
  inputGroup: { marginBottom: "16px" },
  select: { width: "100%", padding: "11px 13px", background: C.bg, border: `1.5px solid ${C.border}`, borderRadius: "9px", color: "#1a1a2e", fontSize: "14px", outline: "none", boxSizing: "border-box" },
  btnPrimary: { background: C.primary, color: "#fff", border: "none", padding: "12px 28px", borderRadius: "10px", fontSize: "14px", fontWeight: "700", cursor: "pointer", width: "100%" },
  btnOutline: { background: "transparent", color: C.primary, border: `1.5px solid ${C.primary}`, padding: "10px 22px", borderRadius: "10px", fontSize: "13px", fontWeight: "600", cursor: "pointer" },
  btnSuccess: { background: C.success, color: "#fff", border: "none", padding: "11px 24px", borderRadius: "10px", fontSize: "14px", fontWeight: "700", cursor: "pointer", width: "100%" },
  btnDanger: { background: C.danger, color: "#fff", border: "none", padding: "9px 20px", borderRadius: "8px", fontSize: "13px", fontWeight: "600", cursor: "pointer" },
  err: { color: C.danger, fontSize: "13px", textAlign: "center", marginBottom: "14px", padding: "10px 14px", background: C.dangerBg, borderRadius: "8px", border: `1px solid #FFCDD2` },
  suc: { color: C.success, fontSize: "13px", textAlign: "center", marginBottom: "14px", padding: "10px 14px", background: C.successBg, borderRadius: "8px", border: `1px solid #A5D6A7` },
  warn: { color: C.warn, fontSize: "13px", marginBottom: "14px", padding: "12px 16px", background: C.warnBg, borderRadius: "8px", border: `1px solid #FFCC80` },
  pageTitle: { fontSize: "26px", fontWeight: "800", color: C.text, marginBottom: "4px" },
  pageSub: { fontSize: "14px", color: C.textSec, marginBottom: "28px" },
  sectionTitle: { fontSize: "17px", fontWeight: "700", color: C.text, marginBottom: "16px" },
  badge: (color, bg) => ({ display: "inline-block", padding: "4px 12px", borderRadius: "20px", fontSize: "12px", fontWeight: "700", background: bg, color }),
  table: { width: "100%", borderCollapse: "collapse", fontSize: "14px" },
  th: { background: C.primaryLight, color: C.primary, padding: "11px 14px", textAlign: "left", fontWeight: "700", fontSize: "12px", textTransform: "uppercase", letterSpacing: "0.5px" },
  td: { padding: "11px 14px", borderBottom: `1px solid ${C.border}`, color: "#1a1a2e" },
  stat: { background: C.card, border: `1px solid ${C.border}`, borderRadius: "12px", padding: "18px 20px", textAlign: "center" },
  statNum: { fontSize: "28px", fontWeight: "900", color: C.primary },
  statLabel: { fontSize: "12px", color: C.textSec, marginTop: "4px", fontWeight: "600" },
  grid3: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: "16px" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" },
  link: { color: C.primary, cursor: "pointer", fontWeight: "600", fontSize: "14px" },
};